import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Bottles",
    slug: "bottles",
    image: "/decorative-bottles-collection.jpg",
  },
  {
    id: "2",
    name: "Soft Toys",
    slug: "soft-toys",
    image: "/cute-soft-toys-plush.jpg",
  },
  {
    id: "3",
    name: "Birthday Gifts",
    slug: "birthday-gifts",
    image: "/birthday-gift-wrapped-present.jpg",
  },
  {
    id: "4",
    name: "Anniversary Gifts",
    slug: "anniversary-gifts",
    image: "/romantic-anniversary-gift.jpg",
  },
  {
    id: "5",
    name: "Photo Frames",
    slug: "photo-frames",
    image: "/elegant-photo-frames.jpg",
  },
  {
    id: "6",
    name: "Personalized Gifts",
    slug: "personalized-gifts",
    image: "/personalized-custom-gift.jpg",
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Rose Gold Water Bottle",
    description:
      "Elegant rose gold stainless steel water bottle, perfect for gifting. Keeps drinks hot for 12 hours and cold for 24 hours.",
    price: 599,
    images: ["/rose-gold-water-bottle-elegant.jpg"],
    category: "bottles",
    badge: "60 Min Delivery",
    inStock: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Giant Teddy Bear",
    description: "Super soft and cuddly giant teddy bear, 4 feet tall. Perfect for birthdays and anniversaries.",
    price: 1499,
    images: ["/giant-brown-teddy-bear-plush.jpg"],
    category: "soft-toys",
    inStock: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Birthday Explosion Box",
    description: "Handcrafted explosion box filled with photos and messages. The perfect surprise for your loved ones.",
    price: 899,
    images: ["/birthday-explosion-gift-box.jpg"],
    category: "birthday-gifts",
    badge: "Best Seller",
    inStock: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Couple Photo Frame",
    description: 'Beautiful wooden photo frame with "Love" engraving. Available in multiple sizes.',
    price: 449,
    images: ["/wooden-couple-photo-frame-love.jpg"],
    category: "photo-frames",
    sizes: [
      { name: "6x8 inch", price: 449 },
      { name: "8x10 inch", price: 599 },
      { name: "12x14 inch", price: 799 },
    ],
    inStock: true,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Anniversary Memory Book",
    description: "Customizable memory book with space for photos, notes, and special memories.",
    price: 699,
    images: ["/anniversary-memory-scrapbook.jpg"],
    category: "anniversary-gifts",
    badge: "Customizable",
    inStock: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Personalized Name Lamp",
    description: "LED lamp with custom name or message. Perfect nightlight for any room.",
    price: 549,
    images: ["/personalized-led-name-lamp.jpg"],
    category: "personalized-gifts",
    inStock: true,
    isNewArrival: true,
    isFestival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Crystal Water Bottle",
    description: "Premium crystal glass water bottle with bamboo lid. Eco-friendly and stylish.",
    price: 799,
    images: ["/crystal-glass-water-bottle-bamboo.jpg"],
    category: "bottles",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Bunny Plush Toy",
    description: "Adorable soft bunny plush toy. Great for kids and adults alike.",
    price: 399,
    images: ["/cute-bunny-plush-toy-soft.jpg"],
    category: "soft-toys",
    badge: "60 Min Delivery",
    inStock: true,
    isFestival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Birthday Cake Topper Set",
    description: 'Golden glitter cake topper set with "Happy Birthday" and decorative elements.',
    price: 249,
    images: ["/golden-birthday-cake-topper.jpg"],
    category: "birthday-gifts",
    inStock: true,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Rose Preserved in Glass",
    description: "Real preserved rose in a glass dome. Lasts for years without water.",
    price: 999,
    images: ["/placeholder.svg?height=400&width=400"],
    category: "anniversary-gifts",
    badge: "Premium",
    inStock: true,
    isFeatured: true,
    isFestival: true,
    createdAt: new Date().toISOString(),
  },
]
